### ISSUE TITLE
Change station icon = crash

### ISSUE THREAD

**Issue by JonnyTech** [y20k/transistor#204]
Even though I have granted the storage permission, selecting the change icon menu item it crashes the app - v3.1.0 from fdroid on Oreo 8.0

**Comment by y20k** [comment]
Hi @JonnyTech,

Thanks for reporting this! I cannot reproduce the issue here. It would be great if you could post step-by-step instructions on how to reproduce. And where exactly the crash occurs.

**Comment by JonnyTech** [comment]
All that I do is click on the change icon menu item for any station, regardless of whether a station is playing or not, and it crashes.

Below is a log in case it helps:

```
11-23 23:44:16.006 V/WindowManager(1050): Set focused app to: AppWindowToken{fe5cd42 token=Token{dbe31f4 ActivityRecord{1b057c7 u0 org.y20k.transistor/.MainActivity t2509}}} old focus=AppWindowToken{fff3d7d token=Token{ef1a7d4 ActivityRecord{7127927 u0 com.android.systemui/.recents.RecentsActivity t2275}}} moveFocusNow=true
11-23 23:44:16.007 V/WindowManager(1050): findFocusedWindow: Reached focused app=AppWindowToken{fe5cd42 token=Token{dbe31f4 ActivityRecord{1b057c7 u0 org.y20k.transistor/.MainActivity t2509}}} target=AppWindowToken{fff3d7d token=Token{ef1a7d4 ActivityRecord{7127927 u0 com.android.systemui/.recents.RecentsActivity t2275}}}
11-23 23:44:16.010 I/vendor.mediatek.hardware.power@1.1-impl(429): notifyAppState pack:org.y20k.transistor, act:org.y20k.transistor.MainActivity, pid:23814, state:1
11-23 23:44:16.011 I/libPerfService(429): [perfNotifyAppState] foreground:org.y20k.transistor, pid:23814
11-23 23:44:16.073 V/PhoneWindow(23814): DecorView setVisiblity: visibility = 0, Parent = ViewRoot{9b54b68 org.y20k.transistor/org.y20k.transistor.MainActivity,ident = 0}, this = DecorView@a058cf4[MainActivity]
11-23 23:44:16.077 I/WindowManager(1050): Relayout Window{5a90faf u0 org.y20k.transistor/org.y20k.transistor.MainActivity}: oldVis=4 newVis=0 focusMayChange = true
11-23 23:44:16.079 I/BufferQueueConsumer(437): [org.y20k.transistor/org.y20k.transistor.MainActivity#0](this:0x75249eb800,id:3829,api:0,p:-1,c:437) setConsumerName: org.y20k.transistor/org.y20k.transistor.MainActivity#0
11-23 23:44:16.079 I/BufferQueueConsumer(437): [org.y20k.transistor/org.y20k.transistor.MainActivity#0](this:0x75249eb800,id:3829,api:0,p:-1,c:437) setDefaultBufferSize: width=720 height=1280
11-23 23:44:16.083 V/WindowManager(1050): Changing focus from null to Window{5a90faf u0 org.y20k.transistor/org.y20k.transistor.MainActivity} Callers=com.android.server.wm.WindowManagerService.relayoutWindow:2179 com.android.server.wm.Session.relayout:235 android.view.IWindowSession$Stub.onTransact:286 com.android.server.wm.Session.onTransact:162 
11-23 23:44:16.084 D/WindowManager(1050): Input focus has changed to Window{5a90faf u0 org.y20k.transistor/org.y20k.transistor.MainActivity}
11-23 23:44:16.093 I/BufferQueueProducer(437): [org.y20k.transistor/org.y20k.transistor.MainActivity#0](this:0x75249eb800,id:3829,api:1,p:23814,c:437) connect(P): api=1 producer=(23814:org.y20k.transistor) producerControlledByApp=true
11-23 23:44:17.047 D/GasService(1756): pkg a:[org.y20k.transistor] [D] pid:23814 uid:10215 audio:0,_s:0
11-23 23:44:17.937 I/BufferQueueProducer(437): [org.y20k.transistor/org.y20k.transistor.MainActivity#0](this:0x75249eb800,id:3829,api:1,p:23814,c:437) queueBuffer: fps=0.56 dur=1786.16 max=1786.16 min=1786.16
11-23 23:44:18.953 I/BufferQueueProducer(437): [org.y20k.transistor/org.y20k.transistor.MainActivity#0](this:0x75249eb800,id:3829,api:1,p:23814,c:437) queueBuffer: fps=21.65 dur=1016.22 max=666.00 min=13.98
11-23 23:44:19.062 V/WindowManager(1050): Changing focus from Window{5a90faf u0 org.y20k.transistor/org.y20k.transistor.MainActivity} to Window{d894241 u0 PopupWindow:ee6575b} Callers=com.android.server.wm.WindowManagerService.addWindow:1587 com.android.server.wm.Session.addToDisplay:200 android.view.IWindowSession$Stub.onTransact:124 com.android.server.wm.Session.onTransact:162 
11-23 23:44:19.083 I/BufferQueueProducer(437): [PopupWindow:ee6575b#0](this:0x752372a800,id:3830,api:1,p:23814,c:437) connect(P): api=1 producer=(23814:org.y20k.transistor) producerControlledByApp=true
11-23 23:44:19.164 I/WindowManager(1050): Losing delayed focus: Window{5a90faf u0 org.y20k.transistor/org.y20k.transistor.MainActivity}
11-23 23:44:20.139 E/MessageQueue-JNI(23814): 	at org.y20k.transistor.MainActivity.k(Unknown Source:10)
11-23 23:44:20.139 E/MessageQueue-JNI(23814): 	at org.y20k.transistor.MainActivity.b(Unknown Source:16)
11-23 23:44:20.139 E/MessageQueue-JNI(23814): 	at org.y20k.transistor.helpers.t$1.onMenuItemClick(Unknown Source:40)
11-23 23:44:20.140 E/AndroidRuntime(23814): Process: org.y20k.transistor, PID: 23814
11-23 23:44:20.140 E/AndroidRuntime(23814): 	at org.y20k.transistor.MainActivity.k(Unknown Source:10)
11-23 23:44:20.140 E/AndroidRuntime(23814): 	at org.y20k.transistor.MainActivity.b(Unknown Source:16)
11-23 23:44:20.140 E/AndroidRuntime(23814): 	at org.y20k.transistor.helpers.t$1.onMenuItemClick(Unknown Source:40)
11-23 23:44:20.149 W/ActivityManager(1050):   Force finishing activity org.y20k.transistor/.MainActivity
11-23 23:44:20.164 I/ActivityManager(1050): Showing crash dialog for package org.y20k.transistor u0
11-23 23:44:20.166 D/AES     (1050): onEndOfErrorDumpThread: data_app_crash Process: org.y20k.transistor
11-23 23:44:20.166 D/AES     (1050): Package: org.y20k.transistor v64 (3.1.0)
11-23 23:44:20.166 D/AES     (1050): 	at org.y20k.transistor.MainActivity.k(Unknown Source:10)
11-23 23:44:20.166 D/AES     (1050): 	at org.y20k.transistor.MainActivity.b(Unknown Source:16)
11-23 23:44:20.166 D/AES     (1050): 	at org.y20k.transistor.helpers.t$1.onMenuItemClick(Unknown Source:40)
11-23 23:44:20.170 D/AES     (1050):     process : org.y20k.transistor
11-23 23:44:20.170 D/AES     (1050):      module : org.y20k.transistor v64 (3.1.0)
11-23 23:44:20.170 D/AEE_LIBAEE(1050): shell: raise_exp(4, 23814, -1361051648, org.y20k.transistor, 0x0x7b04d58f40, 0x0x0)
11-23 23:44:20.184 I/AEE_AED (23990): [preset_info] pid: 23814, tid: -1361051648, name: UNKNOWN  >>> org.y20k.transistor <<<
11-23 23:44:20.185 V/AEE_AED (23990): dashboard_record_update() : rec->module = org.y20k.transistor 
11-23 23:44:20.185 D/AEE_AED (23990): Module: org.y20k.transistor 
11-23 23:44:20.243 D/WindowClient(1050): Add to mViews: DecorView@2255d27[transistor], this = android.view.WindowManagerGlobal@1f1acd
11-23 23:44:20.248 D/ViewRootImpl[transistor](1050): hardware acceleration is enabled, this = ViewRoot{cac89e8 Application Error: org.y20k.transistor,ident = 307}
11-23 23:44:20.251 V/WindowManager(1050): Changing focus from Window{d894241 u0 PopupWindow:ee6575b} to Window{66636a6 u0 Application Error: org.y20k.transistor} Callers=com.android.server.wm.WindowManagerService.addWindow:1587 com.android.server.wm.Session.addToDisplay:200 android.view.ViewRootImpl.setView:840 android.view.WindowManagerGlobal.addView:361 
11-23 23:44:20.253 D/WindowManager(1050): Input focus has changed to Window{66636a6 u0 Application Error: org.y20k.transistor}
11-23 23:44:20.277 I/BufferQueueConsumer(437): [Application Error: org.y20k.transistor#0](this:0x75249df800,id:3831,api:0,p:-1,c:437) setConsumerName: Application Error: org.y20k.transistor#0
11-23 23:44:20.277 I/BufferQueueConsumer(437): [Application Error: org.y20k.transistor#0](this:0x75249df800,id:3831,api:0,p:-1,c:437) setDefaultBufferSize: width=812 height=424
11-23 23:44:20.286 I/StabilityMonitor(22044): [ParserUtility] key word : org.y20k.transistor
11-23 23:44:20.288 I/StabilityMonitor(22044): [APRReport] exceptionItem  tag:data_app_crash packageName:org.y20k.transistor versionCode:64 versionName:3.1.0
11-23 23:44:20.295 I/BufferQueueProducer(437): [Application Error: org.y20k.transistor#0](this:0x75249df800,id:3831,api:1,p:1050,c:437) connect(P): api=1 producer=(1050:system_server) producerControlledByApp=false
11-23 23:44:20.352 E/STBIntentService(22044): send error message:data_app_crash;1543016660165(pkgName:org.y20k.transistor;version:3.1.0;versionCode:64) to BBS for ANR/FC/TOMB_STONE...
11-23 23:44:20.653 W/ActivityManager(1050): Activity pause timeout for ActivityRecord{1b057c7 u0 org.y20k.transistor/.MainActivity t2509 f}
11-23 23:44:20.655 V/WindowManager(1050): Set focused app to: AppWindowToken{5faf025 token=Token{40b4ed8 ActivityRecord{6609bb u0 ch.deletescape.lawnchair.plah/ch.deletescape.lawnchair.Launcher t2259}}} old focus=AppWindowToken{fe5cd42 token=Token{dbe31f4 ActivityRecord{1b057c7 u0 org.y20k.transistor/.MainActivity t2509}}} moveFocusNow=true
11-23 23:44:20.825 I/SurfaceFlinger(437): screenshot (org.y20k.transistor/org.y20k.transistor.MainActivity#0)
11-23 23:44:22.892 W/ActivityManager(1050):   Force finishing activity org.y20k.transistor/.MainActivity
11-23 23:44:22.934 I/BufferQueueConsumer(437): [org.y20k.transistor/org.y20k.transistor.MainActivity#0](this:0x75249eb800,id:3829,api:1,p:23814,c:-1) disconnect(C)
11-23 23:44:22.943 I/ActivityManager(1050): Killing 23814:org.y20k.transistor/u0a215 (adj 900): crash
11-23 23:44:23.037 I/BufferQueueProducer(437): [Application Error: org.y20k.transistor#0](this:0x75249df800,id:3831,api:1,p:1050,c:437) disconnect(P): api 1
11-23 23:44:23.038 I/BufferQueueConsumer(437): [Application Error: org.y20k.transistor#0](this:0x75249df800,id:3831,api:1,p:-1,c:437) getReleasedBuffers: returning mask 0xffffffffffffffff
11-23 23:44:23.054 V/WindowManager(1050): Remove Window{66636a6 u0 Application Error: org.y20k.transistor} client=8eb9801, surfaceController=Surface(name=Application Error: org.y20k.transistor) Callers=com.android.server.wm.WindowState.removeIfPossible:1771 com.android.server.wm.WindowManagerService.removeWindow:1754 com.android.server.wm.Session.remove:219 android.view.ViewRootImpl.dispatchDetachedFromWindow:3915 android.view.ViewRootImpl.doDie:6868 
11-23 23:44:23.056 V/WindowManager(1050): Changing focus from Window{66636a6 u0 Application Error: org.y20k.transistor EXITING} to Window{417a6da u0 ch.deletescape.lawnchair.plah/ch.deletescape.lawnchair.Launcher} Callers=com.android.server.wm.WindowState.setupWindowForRemoveOnExit:1919 com.android.server.wm.WindowState.removeIfPossible:1891 com.android.server.wm.WindowState.removeIfPossible:1771 com.android.server.wm.WindowManagerService.removeWindow:1754 
11-23 23:44:23.074 I/BufferQueueProducer(437): [org.y20k.transistor/org.y20k.transistor.MainActivity#0](this:0x75249eb800,id:3829,api:1,p:23814,c:-1) disconnect(P): api 1
11-23 23:44:23.074 I/BufferQueue(437): [org.y20k.transistor/org.y20k.transistor.MainActivity#0](this:0x75249eb800,id:3829,api:1,p:-1,c:-1) ~BufferQueueCore
11-23 23:44:23.083 D/WindowClient(1050): Remove from mViews: DecorView@2255d27[transistor], this = android.view.WindowManagerGlobal@1f1acd
11-23 23:44:23.253 I/BufferQueueConsumer(437): [Application Error: org.y20k.transistor#0](this:0x75249df800,id:3831,api:1,p:-1,c:-1) disconnect(C)
11-23 23:44:23.253 I/BufferQueue(437): [Application Error: org.y20k.transistor#0](this:0x75249df800,id:3831,api:1,p:-1,c:-1) ~BufferQueueCore
```

I had upgraded from a previous version and station are freshly added.

**Comment by y20k** [comment]
I am still a bit lost. I will try to reproduce the Issue using the emulator and Android 8. My phone runs 8.1 and is not impacted by the bug. If you find the time: Try to downgrade Transistor to see if this is a new bug in v3.1.0. Cheers

**Comment by JonnyTech** [comment]
It seems to be a problem with my device. Downgraded right down to the oldest version on fdroid and the problem exists. My other devices running nougat work well. So not sure what is going on. All other apps work correctly. Shall continue investigating...

**Comment by JonnyTech** [comment]
The problem is that I do not have `Google Photos` enabled. In fact, I have most Google bloatware disabled. Enabling `Google Photos` prevents the crash and lauches `Google Photos` when the menu item is selected.

From what I can work out, `Transistor` is trying to send an **intent** to pick an image:

`Intent pickImageIntent = new Intent(Intent.ACTION_PICK, android.provider.MediaStore.Images.Media.EXTERNAL_CONTENT_URI);`

Looks like none of my other apps can handle that intent and `Transistor` crashes.

As I am not an Android developer, I am guessing that some error trapping needs to go within `onActivityResult` (in `MainActivity.java`). But I have tried and failed to compile `Transistor` myself (some problem with my Linux install that impacts Android Studio which I do not want to fix right now as it looks like it will break other things) so am unable to provide a working pull request.

Happy to try any test builds though.

**Comment by y20k** [comment]
Good work! THX. I was able to reproduce the crash. The next version of Transistor will incorporate a check if there is a Gallery app available on the device. That prevents at least on my phone the crash. If you want to try it out. Here a test APK:

* [transistor-app-testing-3.1.1-001.apk](https://www.dropbox.com/s/ayr6sznaudl807j/transistor-app-testing-3.1.1-001.apk?dl=0)

**Comment by JonnyTech** [comment]
Perfect - that works without crashing - many thanks for the test file (although the Dropbox download mobile experience is awful!). I shall request the the FOSS gallery app that I am using ([Camera Roll](https://github.com/kollerlukas/Camera-Roll-Android-App)) supports the relevant intent.
