### ISSUE TITLE
play/pause button on a wired headset doesn't work every time

### ISSUE THREAD

**Issue by 532910** [y20k/transistor#323]
While it doesn't crash anymore (#229) it still doesn't work always.

Steps:

1. Start playback in SoundCloud or VLC 
2. Stop playback, close the app, clear notification
3. Press play/pause button on a wired headset -> playback will resume from the point it was stopped as expected

1. Start playback in Transistor
2. Stop playback, close the app, clear notification
3. Press play/pause button on a wired headset:
```
D MediaSessionService: Sending KeyEvent { action=ACTION_DOWN, keyCode=KEYCODE_HEADSETHOOK, scanCode=226, metaState=0, flags=0x8, repeatCount=0, eventTime=165572508, downTime=165572508, deviceId=1, source=0x101, displayId=0 } to the last known PendingIntent PendingIntent{8483d1: PendingIntentRecord{27f318e org.y20k.transistor broadcastIntent}}
D MediaSessionService: Sending KeyEvent { action=ACTION_UP, keyCode=KEYCODE_HEADSETHOOK, scanCode=226, metaState=0, flags=0x8, repeatCount=0, eventTime=165572508, downTime=165572508, deviceId=1, source=0x101, displayId=0 } to the last known PendingIntent PendingIntent{8483d1: PendingIntentRecord{27f318e org.y20k.transistor broadcastIntent}}
D Zygote  : Forked child process 28412
I ActivityManager: Start proc 28412:org.y20k.transistor/u0a176 for broadcast {org.y20k.transistor/androidx.media.session.MediaButtonReceiver}
I Zygote  : seccomp disabled by setenforce 0
E y20k.transisto: Not starting debugger since process cannot load the jdwp agent. 
W y20k.transisto: Insufficient pre-allocated space to mmap vdex.
I transistor_a: Theme: Follow System Mode activated.
D MediaBrowserCompat: Connecting to a MediaBrowserService.
I ExoPlayerImpl: Init 861835a [ExoPlayerLib/2.12.0] [OnePlus3T, ONEPLUS A3010, OnePlus, 29]
D MediaSessionService: Media button session is changed to org.y20k.transistor/transistor_PlayerService (userId=0)
V SettingsProvider: Notifying for 0: content://settings/secure/media_button_receiver
D MediaBrowserCompat: Connecting to a MediaBrowserService.
D MediaSessionService: Media button session is changed to null
I ExoPlayerImpl: Release 861835a [ExoPlayerLib/2.12.0] [OnePlus3T, ONEPLUS A3010, OnePlus, 29] [goog.exo.core]
E transistor_j: ===> android.resource://org.y20k.transistor/drawable/ic_default_station_image_24dp
I ExoPlayerImpl: Init ceaa9f1 [ExoPlayerLib/2.12.0] [OnePlus3T, ONEPLUS A3010, OnePlus, 29]
D MediaSessionService: Media button session is changed to org.y20k.transistor/transistor_PlayerService (userId=0)
D MediaSessionService: Media button session is changed to null
I ExoPlayerImpl: Release ceaa9f1 [ExoPlayerLib/2.12.0] [OnePlus3T, ONEPLUS A3010, OnePlus, 29] [goog.exo.core]
E transistor_j: ===> android.resource://org.y20k.transistor/drawable/ic_default_station_image_24dp
W transistor_PlayerService: No station has been selected. Starting playback of last played station.
E transistor_j: ===> file:///storage/emulated/0/Android/data/org.y20k.transistor/files/images/418b922d-b28b-4ba4-b884-a0a74b031c84/station-image-small.jpg
E transistor_j: ===> file:///storage/emulated/0/Android/data/org.y20k.transistor/files/images/418b922d-b28b-4ba4-b884-a0a74b031c84/station-image-small.jpg
W MessageQueue: Handler (android.os.Handler) {4970d74} sending message to a Handler on a dead thread
W MessageQueue: java.lang.IllegalStateException: Handler (android.os.Handler) {4970d74} sending message to a Handler on a dead thread
W MessageQueue:         at android.os.MessageQueue.enqueueMessage(MessageQueue.java:558)
W MessageQueue:         at android.os.Handler.enqueueMessage(Handler.java:754)
W MessageQueue:         at android.os.Handler.sendMessageAtTime(Handler.java:703)
W MessageQueue:         at android.os.Handler.sendMessageDelayed(Handler.java:673)
W MessageQueue:         at android.os.Handler.sendMessage(Handler.java:611)
W MessageQueue:         at android.os.Message.sendToTarget(Message.java:468)
W MessageQueue:         at org.y20k.transistor.PlayerService.preparePlayer(SourceFile:82)
W MessageQueue:         at org.y20k.transistor.PlayerService.startPlayback(SourceFile:9)
W MessageQueue:         at org.y20k.transistor.PlayerService.access$startPlayback(SourceFile:1)
W MessageQueue:         at org.y20k.transistor.PlayerService$e.f(SourceFile:4)
W MessageQueue:         at android.support.v4.media.session.MediaSessionCompat$a$b.d(SourceFile:1)
W MessageQueue:         at j.a.a.b.b.h.onPlay(SourceFile:1)
W MessageQueue:         at android.media.session.MediaSession$Callback.handleMediaPlayPauseKeySingleTapIfPending(MediaSession.java:983)
W MessageQueue:         at android.media.session.MediaSession$Callback.access$800(MediaSession.java:847)
W MessageQueue:         at android.media.session.MediaSession$CallbackMessageHandler.handleMessage(MediaSession.java:1654)
W MessageQueue:         at android.os.Handler.dispatchMessage(Handler.java:107)
W MessageQueue:         at android.os.Looper.loop(Looper.java:214)
W MessageQueue:         at android.app.ActivityThread.main(ActivityThread.java:7356)
W MessageQueue:         at java.lang.reflect.Method.invoke(Native Method)
W MessageQueue:         at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
W MessageQueue:         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:940)
W MessageQueue: Handler (android.os.Handler) {4970d74} sending message to a Handler on a dead thread
W MessageQueue: java.lang.IllegalStateException: Handler (android.os.Handler) {4970d74} sending message to a Handler on a dead thread
W MessageQueue:         at android.os.MessageQueue.enqueueMessage(MessageQueue.java:558)
W MessageQueue:         at android.os.Handler.enqueueMessage(Handler.java:754)
W MessageQueue:         at android.os.Handler.sendMessageAtTime(Handler.java:703)
W MessageQueue:         at android.os.Handler.sendMessageDelayed(Handler.java:673)
W MessageQueue:         at android.os.Handler.sendMessage(Handler.java:611)
W MessageQueue:         at android.os.Message.sendToTarget(Message.java:468)
W MessageQueue:         at org.y20k.transistor.PlayerService.preparePlayer(SourceFile:99)
W MessageQueue:         at org.y20k.transistor.PlayerService.startPlayback(SourceFile:9)
W MessageQueue:         at org.y20k.transistor.PlayerService.access$startPlayback(SourceFile:1)
W MessageQueue:         at org.y20k.transistor.PlayerService$e.f(SourceFile:4)
W MessageQueue:         at android.support.v4.media.session.MediaSessionCompat$a$b.d(SourceFile:1)
W MessageQueue:         at j.a.a.b.b.h.onPlay(SourceFile:1)
W MessageQueue:         at android.media.session.MediaSession$Callback.handleMediaPlayPauseKeySingleTapIfPending(MediaSession.java:983)
W MessageQueue:         at android.media.session.MediaSession$Callback.access$800(MediaSession.java:847)
W MessageQueue:         at android.media.session.MediaSession$CallbackMessageHandler.handleMessage(MediaSession.java:1654)
W MessageQueue:         at android.os.Handler.dispatchMessage(Handler.java:107)
W MessageQueue:         at android.os.Looper.loop(Looper.java:214)
W MessageQueue:         at android.app.ActivityThread.main(ActivityThread.java:7356)
W MessageQueue:         at java.lang.reflect.Method.invoke(Native Method)
W MessageQueue:         at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
W MessageQueue:         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:940)
W transistor_PlayerService: Unhandled player state change. Treat state as: playback stopped by app.
D MediaSessionService: Unknown session changed playback state. Ignoring.
I MediaFocusControl: requestAudioFocus() from uid/pid 10176/28412 clientId=android.media.AudioManager@555dae3l.b.a.a.z$a@cd18ce0 callingPack=org.y20k.transistor req=1 flags=0x0 sdk=29
W MessageQueue: Handler (android.os.Handler) {4970d74} sending message to a Handler on a dead thread
W MessageQueue: java.lang.IllegalStateException: Handler (android.os.Handler) {4970d74} sending message to a Handler on a dead thread
W MessageQueue:         at android.os.MessageQueue.enqueueMessage(MessageQueue.java:558)
W MessageQueue:         at android.os.Handler.enqueueMessage(Handler.java:754)
W MessageQueue:         at android.os.Handler.sendMessageAtTime(Handler.java:703)
W MessageQueue:         at android.os.Handler.sendMessageDelayed(Handler.java:673)
W MessageQueue:         at android.os.Handler.sendMessage(Handler.java:611)
W MessageQueue:         at android.os.Message.sendToTarget(Message.java:468)
W MessageQueue:         at l.b.a.a.h0.w(SourceFile:8)
W MessageQueue:         at l.b.a.a.g1.u(SourceFile:1)
W MessageQueue:         at l.b.a.a.g1.s(SourceFile:4)
W MessageQueue:         at org.y20k.transistor.PlayerService.startPlayback(SourceFile:10)
W MessageQueue:         at org.y20k.transistor.PlayerService.access$startPlayback(SourceFile:1)
W MessageQueue:         at org.y20k.transistor.PlayerService$e.f(SourceFile:4)
W MessageQueue:         at android.support.v4.media.session.MediaSessionCompat$a$b.d(SourceFile:1)
W MessageQueue:         at j.a.a.b.b.h.onPlay(SourceFile:1)
W MessageQueue:         at android.media.session.MediaSession$Callback.handleMediaPlayPauseKeySingleTapIfPending(MediaSession.java:983)
W MessageQueue:         at android.media.session.MediaSession$Callback.access$800(MediaSession.java:847)
W MessageQueue:         at android.media.session.MediaSession$CallbackMessageHandler.handleMessage(MediaSession.java:1654)
W MessageQueue:         at android.os.Handler.dispatchMessage(Handler.java:107)
W MessageQueue:         at android.os.Looper.loop(Looper.java:214)
W MessageQueue:         at android.app.ActivityThread.main(ActivityThread.java:7356)
W MessageQueue:         at java.lang.reflect.Method.invoke(Native Method)
W MessageQueue:         at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
W MessageQueue:         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:940)
D MediaSessionService: Unknown session changed playback state. Ignoring.
W MediaSessionService: Unknown session updated. Ignoring.
I WifiService: acquireWifiLock uid=10176 lockMode=3
E transistor_j: ===> file:///storage/emulated/0/Android/data/org.y20k.transistor/files/images/418b922d-b28b-4ba4-b884-a0a74b031c84/station-image-small.jpg
```

v4.0.7, lineageos 17.1 + microg, op3t

**Comment by y20k** [comment]
@532910 

Not sure if related: But I identified an issue that the system kills Transistor (the notification disappears / logcat "Stopping service due to app idle"). 

If that happens, signals coming from headphone do not reach Transistor anymore.

**Comment by 532910** [comment]
> Not sure if related

Hope this is related!


```
# logcat | grep 'Stopping service due to app idle' | grep y20k | wc -l
11
```
