### ISSUE TITLE
Find a crash and a bug!

### ISSUE THREAD

**Issue by LvZW1895** [y20k/transistor#353]
**Describe the bug**
When you quickly swipe up the bottom when the app was just launched, a window appears that shouldn't be there.
**Screenshots**
![image](https://user-images.githubusercontent.com/31195211/114295209-42d70a00-9ad6-11eb-8911-e6fc73221e56.png)

**Crash**
A crashes happened by accident  in the settings page when I was using it. I tried to reproduce it and found that it is difficult to be reproduced, but they are real. I hope it can help you to debug.

Long Msg: android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.VIEW dat=https://github.com/... }
	at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:2058)
	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1716)
	at android.app.Activity.startActivityForResult(Activity.java:5211)
	at androidx.activity.ComponentActivity.startActivityForResult(ComponentActivity.java:570)
	at androidx.fragment.app.FragmentActivity.startActivityForResult(FragmentActivity.java:675)
	at androidx.core.app.ActivityCompat.startActivityForResult(ActivityCompat.java:234)
	at androidx.fragment.app.FragmentActivity.startActivityFromFragment(FragmentActivity.java:790)
	at androidx.fragment.app.FragmentActivity$HostCallbacks.onStartActivityFromFragment(FragmentActivity.java:932)
	at androidx.fragment.app.Fragment.startActivity(Fragment.java:1257)
	at androidx.fragment.app.Fragment.startActivity(Fragment.java:1245)
	at org.y20k.transistor.SettingsFragment$onCreatePreferences$6.onPreferenceClick(SettingsFragment.kt:147)
	at androidx.preference.Preference.performClick(Preference.java:1184)
	at androidx.preference.Preference.performClick(Preference.java:1166)
	at androidx.preference.Preference$1.onClick(Preference.java:181)
	at android.view.View.performClick(View.java:7259)
	at android.view.View.performClickInternal(View.java:7236)
	at android.view.View.access$3600(View.java:801)
	at android.view.View$PerformClick.run(View.java:27892)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7356)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)

**Device:**
 - Device: [e.g. OnePlus 5] Google Pixel 2
 - OS: [e.g. Lineage OS 16.0] Android 9.0
 - Version [e.g. v4.0] 4.0.14

**Comment by y20k** [comment]
@LvZW1895 
thanks for reporting those two bugs. If you find a way to reproduce the crash please let me know.
